"""add_run_and_backlog_to_deploy_outcomes

Revision ID: 40b39dbac1f6
Revises: 26462c37c7ef
Create Date: 2026-09-07 00:08:19.654745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b39dbac1f6'
down_revision: Union[str, Sequence[str], None] = '26462c37c7ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment_outcomes', sa.Column('agent_run_id', sa.UUID(), nullable=True))
    op.add_column('deployment_outcomes', sa.Column('backlog_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'deployment_outcomes', 'backlog', ['backlog_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'deployment_outcomes', 'agent_runs', ['agent_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deployment_outcomes', type_='foreignkey')
    op.drop_constraint(None, 'deployment_outcomes', type_='foreignkey')
    op.drop_column('deployment_outcomes', 'backlog_id')
    op.drop_column('deployment_outcomes', 'agent_run_id')
    # ### end Alembic commands ###
