"""add adrs table

Revision ID: aaa20863cb97
Revises: 05fafaf2ffb8
Create Date: 2026-07-20 21:41:25.039607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'aaa20863cb97'
down_revision: Union[str, Sequence[str], None] = '05fafaf2ffb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adrs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('consequences', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='proposed', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adrs_project_id'), 'adrs', ['project_id'], unique=False)
    # ### end Alembic commands ###
    # NOTA: o autogenerate também detectou DROP de chat_sessions/chat_messages
    # porque esses modelos não estão importados em alembic/env.py (gap
    # pré-existente — o router chat_sessions.py usa SQL direto, sem model
    # SQLAlchemy). Removido manualmente para não apagar o histórico do AI Hub.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adrs_project_id'), table_name='adrs')
    op.drop_table('adrs')
    # ### end Alembic commands ###
